[package]

name = "forced_fracture"
version = "0.0.1"
authors = ["walter"]

[dependencies]
gl = "*"
libc = "*"
glutin = "*"
glium = "*"
image = "*"
time = "*"

#[dependencies.glium]
#git = "https://github.com/tomaka/glium"

#[dependencies.glutin]
#git = "https://github.com/tomaka/glutin"
